version: 0.2
phases:
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - aws codeartifact login --tool twine --domain tregoat-packages --domain-owner $AWS_ACCOUNT_ID --repository age-distribution
  build:
    commands:
      - twine upload --repository codeartifact age-distribution
